### ISSUE TITLE
review comments - security (0.1)

### ISSUE THREAD

**Issue by sfu5** [riscv-non-isa/server-soc#37]
There is no requirement about security RoT in v0.1 spec. Recommand to add:
- To support secure (verified) boot, the SoC must contain immutable boot code (e.g. ROM, OTP) as the RoT for verification. 
- The SoC should provide capability for immutable security parameter provisioning, such as public key for secure boot verification, and possible private key for confidential data decryption.

**Comment by ved-rivos** [comment]
Thank you. This was omitted due to the requirements being covered by the RISC-V security [model](https://github.com/riscv-non-isa/riscv-security-model/blob/main/specification/src/chapter2.adoc) . The security model provides recipes for various security models. I think the security section of the Server SoC specification can be improved with a more explicit reference to the security model but avoid redundancy by repeating the requirements. I will propose an update in a PR shortly.

**Comment by sfu5** [comment]
> Thank you. This was omitted due to the requirements being covered by the RISC-V security [model](https://github.com/riscv-non-isa/riscv-security-model/blob/main/specification/src/chapter2.adoc) . The security model provides recipes for various security use cases. I think the security section of the Server SoC specification can be improved with a more explicit reference to the security model but avoid redundancy by repeating the requirements. I will propose an update in a PR shortly.

That's good to reference existing security mode spec to avoid redundancy, but it's better to explicit mention that and list which secuirty requirement should be implemented for a Server SoC, or all of that in security model.

**Comment by ved-rivos** [comment]
@sfu5 thanks. I have provided cross references to the security model in SEC_005 through SEC_007 in [this commit](https://github.com/riscv-non-isa/server-soc/pull/35/commits/e5cfa8dade834fffafe187a32c3f6dc06587a73c)

**Comment by ved-rivos** [comment]
Please reopen if there is further feedback.
